# Generated by Django 5.2.7 on 2025-11-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_restaurant_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RemoveField(
            model_name='dish',
            name='dish_category',
        ),
        migrations.AddField(
            model_name='dish',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Select multiple categories for this dish', to='core.category'),
        ),
    ]
