# Generated by Django 5.2.7 on 2025-11-19 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_default_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='price',
        ),
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dishes/'),
        ),
        migrations.CreateModel(
            name='DishServing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving_size', models.CharField(choices=[('solo', 'Solo'), ('sharing', 'Sharing (2-3 pax)'), ('family', 'Family (4-6 pax)'), ('party', 'Party (8+ pax)')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servings', to='core.dish')),
            ],
            options={
                'unique_together': {('dish', 'serving_size')},
            },
        ),
    ]
