# Generated by Django 5.2.7 on 2025-11-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_dish_price_dish_image_dishserving'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('video', models.FileField(blank=True, null=True, upload_to='about/')),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Content',
            },
        ),
    ]
